export enum ROUTES {
    BASE = '/',
    OVERVIEW = '/overview',
    LOGIN = '/login',
    SIGNUP = '/signup',
    FORGOT_PASSWORD = '/forgot-password',
    RESET_PASSWORD = '/reset-password',
    VERIFY_EMAIL = '/verify-email',
    NOT_FOUND = '/not-found',
    SERVER_ERROR = '/server-error',
    AUTOMATION = '/automation',
    DASHBOARD = '/dashboard',
    SETTINGS = '/settings',
    KEYWORDS = '/keywords',
    REPORTS = '/reports',
}