export const ROUTES = {
    BASE: '/',
    OVERVIEW: '/overview',
    LOGIN: '/login',
    SIGNUP: '/signup',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
    VERIFY_EMAIL: '/verify-email',
    NOT_FOUND: '/not-found',
    SERVER_ERROR: '/server-error',
    AUTOMATION: '/automation',
    DASHBOARD: '/dashboard',
    WORD_SEEK: "/word-seek",
    SETTINGS: '/settings',
    KEYWORDS: '/keywords',
    REPORTS: '/reports',
    DEVELOPER: '/developer',
    FAQS: '/faqs',
    CONTENT_STRATEGY: '/content-strategy',
    PERFORMANCE: '/performance',
    DEMO_QUESTIONS_ASKED: '/demo/people-also-asked',
    TASK: (id: number) => `/task/${id}`,
}