export const engineUrls = {
    MISSING_KEYWORDS: 'engine/missing-keywords-job',
    PEOPLE_ALSO_ASK: 'engine/people-also-ask/',
    SEED_KEYWORDS: 'engine/keyword-research/',
    CLUSTER_KEYWORDS: 'engine/cluster-keywords/',
    KEYWORD_THEMES: (teamUid?: string) => `engine/keyword-themes${teamUid ? `?team_uid=${teamUid}` : '/'}`,
    GENERATE_SEED_KEYWORDS: 'engine/generate-seed-keywords/',
    BULK_CREATE_SEED_KEYWORDS: 'engine/bulk-create-seed-keywords/',
    BROAD_KEYWORD_API: 'engine/generate-broad-keywords/',
    GENERATE_KI_INPUT: 'engine/generate-ki-input/',
    WORD_SEEK: 'engine/word-seek/',
    WORD_SEEK_RESULTS: (teamId: number, jobGroup?: number | null) => {
        return `/engine/word-seek/results?team_id=${teamId}${jobGroup ? `&job_group=${jobGroup}` : ''}`
    },
    WORD_SEEK_JOBS: (teamId?: number) => `engine/word-seek/jobs${teamId ? `?team_id=${teamId}` : ''}`,
    WORD_SEEK_TRIGGER_JOB: "engine/word-seek/trigger-job",
    WORD_SEEK_RESUME: "engine/word-seek/resume",
    GENERATE_FAQS: (teamId: number, resultId: number) => `wordseek/generate-faqs/?team_id=${teamId}&result_id=${resultId}`,
    FIND_SIMILAR_KEYWORDS: "wordseek/find-similar-keywords/",
    RETRIEVE_SIMILAR_KEYWORDS: (similarKeywordId: number) => `wordseek/similar-keywords/${similarKeywordId}/`,
    UPDATE_MISSPELLED_KEYWORDS: "wordseek/update-misspelled-keywords/",
    GENERATE_INSERT_QUERIES: "wordseek/generate-insert-queries/",
    RETRIEVE_INSERT_QUERY: (insertQueryId: number) => `wordseek/insert-query/${insertQueryId}/`,
    KEYWORD_INSIGHTS_RESULTS: (orderId: number) => `engine/keyword-insights/results?&order_id=${orderId}`,
    CREATE_KEYWORD_INSIGHTS_ORDER: 'engine/keyword-insights/order/',
    KEYWORD_INSIGHTS_ORDER: (contentStrategyId: number) => `engine/keyword-insights/order?content_strategy_id=${contentStrategyId}`,
}